version: '3'
services:

  #PHP Service 7.4
  stockdepot:
    build:
      context: .
      dockerfile: Dockerfile
    image: php74
    container_name: stockdepot
    tty: true
    environment:
      SERVICE_NAME: stockdepot
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../:/var/www:delegated
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated
    networks:
      - stockdepot_network

  #Nginx Service
  stockdepot_webserver:
    image: nginx:alpine
    container_name: stockdepot_webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www:delegated
      - ./nginx/conf.d/:/etc/nginx/conf.d/:delegated
      - ./nginx/certs:/etc/nginx/certs:delegated
    networks:
      - stockdepot_network

  #MySQL5.7 Service
  stockdepot_db:
    image: mysql:5.7
    container_name: stockdepot_db
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - stockdepot_db_data:/var/lib/mysql/:delegated
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - stockdepot_network

#Docker Networks
networks:
  stockdepot_network:
    driver: bridge

#Volumes
volumes:
  stockdepot_db_data:
    driver: local